### ISSUE TITLE
JS Distribution file does not match src file

### ISSUE THREAD

**Issue by seansd** [StonyHillSoftware/guid-factory#1]
Compare the two lines:

https://github.com/StonyHillSoftware/guid-factory/blob/main/dist/Guid.js#L45

https://github.com/StonyHillSoftware/guid-factory/blob/main/lib/Guid.ts#L44

You'll notice that the method `full` in the JS src distribution is missing a segment of the guid string.

**Comment by dperish** [comment]
Sorry, haven't been receiving notifications for this organization for some reason. Will review this shortly.
